language: c
matrix:
  fast_finish: true
  include:
    # OS X Mavericks
    - os: osx
      env: CC_COMPILER=clang

    # Container-based Ubuntu 12.04 LTS Server Edition 64 bit (doesn't support 32-bit includes)
    - os: linux
      sudo: false
      env: CC_COMPILER=gcc

    - os: linux
      sudo: false
      env: CC_COMPILER=clang

    # Ubuntu 14.04 LTS Server Edition 64 bit
    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-aarch64-linux-gnu
            - g++-aarch64-linux-gnu
      env: QEMU_INTERPRETER=qemu-aarch64-static CC_COMPILER=aarch64-linux-gnu-gcc

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-arm
            - qemu-user-static
            - gcc-arm-linux-gnueabi
            - g++-arm-linux-gnueabi
      env: QEMU_INTERPRETER=qemu-arm-static CC_COMPILER=arm-linux-gnueabi-gcc

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: QEMU_INTERPRETER=qemu-ppc64-static CC_COMPILER=powerpc-linux-gnu-gcc

    - dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - qemu-system-ppc
            - qemu-user-static
            - gcc-powerpc-linux-gnu
            - g++-powerpc-linux-gnu
      env: QEMU_INTERPRETER=qemu-ppc-static CC_COMPILER=powerpc-linux-gnu-gcc

    - dist: trusty
      sudo: required
      env: CC_COMPILER=gcc

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CC_COMPILER=gcc-4.9

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CC_COMPILER=gcc-5

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CC_COMPILER=gcc-6

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env: CC_COMPILER=clang-3.5

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - clang-3.6
      env: CC_COMPILER=clang-3.6

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
      env: CC_COMPILER=clang-3.8

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env: CC_COMPILER=clang-3.9

    - dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: CC_COMPILER=clang-4.0

before_install:
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-macosx.tar.gz -O premake.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz -O premake.tar.gz; fi

script:
  - tar zxvf premake.tar.gz
  - ./premake5 gmake
  - make CC=CC_COMPILER
  - $QEMU_INTERPRETER ./bin/Release/benchmark -f
